parameters:
#    ftc56_forum.example.class: FTC56\ForumBundle\Example

services:
#    ftc56_forum.example:
#        class: %ftc56_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
