ftc56_private_message:
    resource: "@FTC56PrivateMessageBundle/Resources/config/routing.yml"
    prefix:   /mp

ftc56_blog:
    resource: "@FTC56BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

ftc56_user:
    resource: "@FTC56UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

home:
    resource: "@FTC56BlogBundle/Resources/config/routing-home.yml"