parameters:
#    ftc56_editor.example.class: FTC56\EditorBundle\Example

services:
#    ftc56_editor.example:
#        class: %ftc56_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
