<?php

namespace FTC56\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getPosts($id)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.topic = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult();
    }
}
