
user_view:
    pattern: /{id}
    defaults: { _controller: FTC56UserBundle:Profile:view }
    requirements:
        id: \d+

user_contact:
    pattern: /{id}/contact
    defaults: { _controller: FTC56UserBundle:Profile:contact }
    requirements:
        id: \d+
