blog_index:
    pattern: /page{page}
    defaults: { _controller: FTC56BlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d+

blog_view:
    pattern: /a/{id}
    defaults: { _controller: FTC56BlogBundle:Blog:view }
    requirements:
        id: \d+

blog_add:
    pattern: /a/add
    defaults: { _controller: FTC56BlogBundle:Blog:add }

blog_delete:
    pattern: /a/{id}/delete
    defaults: { _controller: FTC56BlogBundle:Blog:delete }
    requirements:
        id: \d+

blog_edit:
    pattern: /a/{id}/edit
    defaults: { _controller: FTC56BlogBundle:Blog:edit }
    requirements:
        id: \d+

categories_list:
    pattern: /categories/list
    defaults: { _controller: FTC56BlogBundle:Categories:list }

categories_view:
    pattern: /categories/{id}
    defaults: { _controller: FTC56BlogBundle:Categories:view }
    requirements:
        id: \d+

categories_add:
    pattern: /categories/add
    defaults: { _controller: FTC56BlogBundle:Categories:add }

categories_edit:
    pattern: /categories/{id}/edit
    defaults: { _controller: FTC56BlogBundle:Categories:edit }
    requirements:
        id: \d+

categories_delete:
    pattern: /categories/{id}/delete
    defaults: { _controller: FTC56BlogBundle:Categories:delete }
    requirements:
        id: \d+

comment_edit:
    pattern: /c/{id}/edit
    defaults: { _controller: FTC56BlogBundle:Comment:edit }
    requirements:
        id: \d+

comment_delete:
    pattern: /c/{id}/delete
    defaults: { _controller: FTC56BlogBundle:Comment:delete }
    requirements:
        id: \d+
