<?php

namespace FTC56\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /*public function pagination()
    {
        $articles = $this->_em->createQueryBuilder('a');

        $articles
        ->setFirstResult(1)
        ->setMaxResults(3);

        // $nbArticle = $this->_em->createQueryBuilder('a');

        // $nbArticle->addSelect('count(a)');

        return $articles->getQuery()->getResult();
            //'nbArticles' => $nbArticle->getQuery()->getSingleScalarResult()
    }*/
}
