<?php

namespace FTC56\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function nbComment($id)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
        ->select('FTC56BlogBundle:Article', 'a')
        ->where('a.id = :id')
        ->setParameter('id', $id)
        ->leftJoin('a.commentaires', 'c')
        ->addSelect('count(c)');
    }
}
