parameters:
#    ftc56_private_message.example.class: FTC56\PrivateMessageBundle\Example

services:
#    ftc56_private_message.example:
#        class: %ftc56_private_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
